/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacuradoria;

import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class Cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        cadastroPasswordField1 = new javax.swing.JPasswordField();
        cadastroTextFieldName = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        cadastroTextFieldEmail = new javax.swing.JTextField();
        cadastroTextFieldIdade = new javax.swing.JTextField();
        cadastroPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        cadastroPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPasswordField1ActionPerformed(evt);
            }
        });

        cadastroTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroTextFieldName.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        cadastroTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTextFieldNameActionPerformed(evt);
            }
        });

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        cadastroTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroTextFieldEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        cadastroTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTextFieldEmailActionPerformed(evt);
            }
        });

        cadastroTextFieldIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroTextFieldIdade.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade"));
        cadastroTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTextFieldIdadeActionPerformed(evt);
            }
        });
        cadastroTextFieldIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadastroTextFieldIdadeKeyTyped(evt);
            }
        });

        cadastroPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPasswordField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirme sua senha"));
        cadastroPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPasswordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cadastroPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cadastroTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPasswordField1ActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        String nome = cadastroTextFieldName.getText();
        String email = cadastroTextFieldEmail.getText();
        
        int idade = 0;
        try{
            idade = Integer.parseInt(cadastroTextFieldIdade.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "A idade deve ser um número válido", "Erro de entrada", JOptionPane.ERROR_MESSAGE);
        }
        
        String senha1 = new String(cadastroPasswordField1.getPassword());
        String senha2 = new String(cadastroPasswordField2.getPassword());
        
        if(senha1.equals(senha2)){
            User novoUsuario = new User();
            
            novoUsuario.setNome(nome);
            novoUsuario.setIdade(idade);
            novoUsuario.setTipo("Comum");
            novoUsuario.setSenha(senha1);
            novoUsuario.setEmail(email);
            
            int idNovoUsuario = novoUsuario.cadastrar();
            
            if(idNovoUsuario > 0){
                TelaInteresse telaInteresse = new TelaInteresse(idNovoUsuario);
                
                telaInteresse.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao salvar usuário. Tente novamente.", "Erro no Banco", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "As senhas não conferem. Tente novamwente.");
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void cadastroTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroTextFieldNameActionPerformed

    private void cadastroTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroTextFieldEmailActionPerformed

    private void cadastroTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroTextFieldIdadeActionPerformed

    private void cadastroPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPasswordField2ActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cadastroTextFieldIdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroTextFieldIdadeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        // !Character é uma classe utilitária do java; .isDigit verifica se o valor recebido é um número, se for diferente de número passa.
        if (!Character.isDigit(c) || cadastroTextFieldIdade.getText().length() >= 3){
            evt.consume(); // deleta tudo que não for número.
        }
    }//GEN-LAST:event_cadastroTextFieldIdadeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JPasswordField cadastroPasswordField1;
    private javax.swing.JPasswordField cadastroPasswordField2;
    private javax.swing.JTextField cadastroTextFieldEmail;
    private javax.swing.JTextField cadastroTextFieldIdade;
    private javax.swing.JTextField cadastroTextFieldName;
    private javax.swing.JButton cancelarButton;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
