/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacuradoria;

import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class CadastroPorAdm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroPorAdm.class.getName());

    /**
     * Creates new form CadastroPorAdm
     */
    public CadastroPorAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroPorAdmTextFieldName = new javax.swing.JTextField();
        cadastroPorAdmTextFieldEmail = new javax.swing.JTextField();
        cadastroPorAdmTextFieldIdade = new javax.swing.JTextField();
        cadastroPorAdmPasswordField1 = new javax.swing.JPasswordField();
        cadastroPorAdmPasswordField2 = new javax.swing.JPasswordField();
        cancelarButton = new javax.swing.JButton();
        cadastrarPorAdmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroPorAdmTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPorAdmTextFieldName.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        cadastroPorAdmTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPorAdmTextFieldNameActionPerformed(evt);
            }
        });

        cadastroPorAdmTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPorAdmTextFieldEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        cadastroPorAdmTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPorAdmTextFieldEmailActionPerformed(evt);
            }
        });

        cadastroPorAdmTextFieldIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPorAdmTextFieldIdade.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade"));
        cadastroPorAdmTextFieldIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPorAdmTextFieldIdadeActionPerformed(evt);
            }
        });
        cadastroPorAdmTextFieldIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadastroPorAdmTextFieldIdadeKeyTyped(evt);
            }
        });

        cadastroPorAdmPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPorAdmPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        cadastroPorAdmPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPorAdmPasswordField1ActionPerformed(evt);
            }
        });

        cadastroPorAdmPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastroPorAdmPasswordField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirme sua senha"));
        cadastroPorAdmPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPorAdmPasswordField2ActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        cadastrarPorAdmButton.setText("Cadastrar");
        cadastrarPorAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPorAdmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarPorAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cadastroPorAdmPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroPorAdmTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroPorAdmTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroPorAdmTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastroPorAdmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cadastroPorAdmTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroPorAdmTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroPorAdmTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroPorAdmPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cadastroPorAdmPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarPorAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroPorAdmTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPorAdmTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPorAdmTextFieldNameActionPerformed

    private void cadastroPorAdmTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPorAdmTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPorAdmTextFieldEmailActionPerformed

    private void cadastroPorAdmTextFieldIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPorAdmTextFieldIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPorAdmTextFieldIdadeActionPerformed

    private void cadastroPorAdmTextFieldIdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastroPorAdmTextFieldIdadeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        // !Character é uma classe utilitária do java; .isDigit verifica se o valor recebido é um número, se for diferente de número passa.
        if (!Character.isDigit(c) || cadastroPorAdmTextFieldIdade.getText().length() >= 3){
            evt.consume(); // deleta tudo que não for número.
        }
    }//GEN-LAST:event_cadastroPorAdmTextFieldIdadeKeyTyped

    private void cadastroPorAdmPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPorAdmPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPorAdmPasswordField1ActionPerformed

    private void cadastroPorAdmPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPorAdmPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroPorAdmPasswordField2ActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void cadastrarPorAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPorAdmButtonActionPerformed
        // TODO add your handling code here:
        String nome = cadastroPorAdmTextFieldName.getText();
        String email = cadastroPorAdmTextFieldEmail.getText();

        int idade = 0;
        try{
            idade = Integer.parseInt(cadastroPorAdmTextFieldIdade.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "A idade deve ser um número válido", "Erro de entrada", JOptionPane.ERROR_MESSAGE);
        }

        String senha1 = new String(cadastroPorAdmPasswordField1.getPassword());
        String senha2 = new String(cadastroPorAdmPasswordField2.getPassword());

        if(senha1.equals(senha2)){
            User novoUsuario = new User();

            novoUsuario.setNome(nome);
            novoUsuario.setIdade(idade);
            novoUsuario.setTipo("Comum");
            novoUsuario.setSenha(senha1);
            novoUsuario.setEmail(email);

            int idNovoUsuario = novoUsuario.cadastrar();

            if(idNovoUsuario > 0){
                TelaInteressePorAdm telaInteresse = new TelaInteressePorAdm(idNovoUsuario);

                telaInteresse.setVisible(true);
                telaInteresse.setLocationRelativeTo(null);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao salvar usuário. Tente novamente.", "Erro no Banco", JOptionPane.ERROR_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(this, "As senhas não conferem. Tente novamwente.");
        }
    }//GEN-LAST:event_cadastrarPorAdmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroPorAdm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarPorAdmButton;
    private javax.swing.JPasswordField cadastroPorAdmPasswordField1;
    private javax.swing.JPasswordField cadastroPorAdmPasswordField2;
    private javax.swing.JTextField cadastroPorAdmTextFieldEmail;
    private javax.swing.JTextField cadastroPorAdmTextFieldIdade;
    private javax.swing.JTextField cadastroPorAdmTextFieldName;
    private javax.swing.JButton cancelarButton;
    // End of variables declaration//GEN-END:variables
}
