package com.mycompany.sistemacuradoria;

import java.sql.Connection;
import java.sql.PreparedStatement;

public class EditarUserAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarUserAdmin.class.getName());

    private User userAtual;
    
    /**
     * Creates new form EditarUsuarioAdmin
     */
    public EditarUserAdmin() {
        initComponents();
    }
    
    public EditarUserAdmin(User user){
        initComponents();
        this.userAtual = user;
        carregarDadosUser();
    }
    
    public void carregarDadosUser(){
        if(userAtual != null){
            admEditarNomeTextField.setText(userAtual.getNome());
            admEditarEmailTextField.setText(userAtual.getEmail());
            admEditarIdadeTextField.setText(String.valueOf(userAtual.getIdade()));
            
            String tipo = userAtual.getTipo();
            
            if("Comum".equals(tipo)){
                admTipoComumCheckBox.setSelected(true);
                admTipoAdminCheckBox.setSelected(false);
            } else if("Administrador".equals(tipo)){
                admTipoComumCheckBox.setSelected(false);
                admTipoAdminCheckBox.setSelected(true);
            }
        } else{
            System.err.println("Erro: Tentativa de abrir tela de edição sem nenhum user.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admEditarNomeTextField = new javax.swing.JTextField();
        admEditarEmailTextField = new javax.swing.JTextField();
        admEditarIdadeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        admTipoComumCheckBox = new javax.swing.JCheckBox();
        admTipoAdminCheckBox = new javax.swing.JCheckBox();
        admCancelarButton = new javax.swing.JButton();
        admSalvarButton = new javax.swing.JButton();
        admDeletarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admEditarNomeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        admEditarNomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admEditarNomeTextFieldActionPerformed(evt);
            }
        });

        admEditarEmailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        admEditarEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admEditarEmailTextFieldActionPerformed(evt);
            }
        });

        admEditarIdadeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade"));
        admEditarIdadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admEditarIdadeTextFieldActionPerformed(evt);
            }
        });
        admEditarIdadeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                admEditarIdadeTextFieldKeyTyped(evt);
            }
        });

        jTextPane1.setText("Tipo do usuário:");
        jScrollPane1.setViewportView(jTextPane1);

        admTipoComumCheckBox.setText("Comum");
        admTipoComumCheckBox.setToolTipText("");
        admTipoComumCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admTipoComumCheckBoxActionPerformed(evt);
            }
        });

        admTipoAdminCheckBox.setText("Administrador");
        admTipoAdminCheckBox.setToolTipText("");
        admTipoAdminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admTipoAdminCheckBoxActionPerformed(evt);
            }
        });

        admCancelarButton.setText("Cancelar");
        admCancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admCancelarButtonActionPerformed(evt);
            }
        });

        admSalvarButton.setText("Salvar");
        admSalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admSalvarButtonActionPerformed(evt);
            }
        });

        admDeletarButton.setText("Deletar");
        admDeletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admDeletarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admEditarNomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(admEditarEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(admCancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admSalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(admTipoComumCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admTipoAdminCheckBox))
                    .addComponent(admEditarIdadeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(admDeletarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(admEditarNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(admEditarEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(admEditarIdadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admTipoComumCheckBox)
                    .addComponent(admTipoAdminCheckBox))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admCancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admSalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(admDeletarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admEditarEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admEditarEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admEditarEmailTextFieldActionPerformed

    private void admTipoComumCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admTipoComumCheckBoxActionPerformed
        // TODO add your handling code here:
        
        if(admTipoComumCheckBox.isSelected()){
            admTipoAdminCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_admTipoComumCheckBoxActionPerformed

    private void admTipoAdminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admTipoAdminCheckBoxActionPerformed
        // TODO add your handling code here:
        if(admTipoAdminCheckBox.isSelected()){
            admTipoComumCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_admTipoAdminCheckBoxActionPerformed

    private void admCancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admCancelarButtonActionPerformed
        // TODO add your handling code here:
        TabelaUsersAdmin telaTabelaAdmin = new TabelaUsersAdmin();
        telaTabelaAdmin.setVisible(true);
        telaTabelaAdmin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_admCancelarButtonActionPerformed

    private void admSalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admSalvarButtonActionPerformed
        // TODO add your handling code here:
        String sql = "update tb_user set nome = ?, idade = ?, email = ?, tipo = ? where id_user = ?";
        
        
        String novoNome = admEditarNomeTextField.getText();
        int novaIdade = Integer.parseInt(admEditarIdadeTextField.getText());
        String novoEmail = admEditarEmailTextField.getText();
        String novoTipo;
        
        if(admTipoAdminCheckBox.isSelected()){
            novoTipo = admTipoAdminCheckBox.getText();
        } else if(admTipoComumCheckBox.isSelected()){
            novoTipo = admTipoComumCheckBox.getText();
        } else{
            System.err.println("Não existe esse tipo de usuário no db.");
            return;
        }
        
        ConnectionFactory factory = new ConnectionFactory();
        
        try(Connection c = factory.obtemConexao();
            PreparedStatement ps = c.prepareStatement(sql)){
            
            ps.setString(1, novoNome);
            ps.setInt(2, novaIdade);
            ps.setString(3, novoEmail);
            ps.setString(4, novoTipo);
            ps.setInt(5, userAtual.getId_user());
            
            ps.executeUpdate();
            
            TabelaUsersAdmin telaTabelaAdmin = new TabelaUsersAdmin();
            telaTabelaAdmin.setVisible(true);
            telaTabelaAdmin.setLocationRelativeTo(null);
            this.dispose();
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar alterações: " + e.getMessage(), "Erro de Banco", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_admSalvarButtonActionPerformed

    private void admDeletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admDeletarButtonActionPerformed
        // TODO add your handling code here:
        String sql = "delete from tb_user where id_user = ?";
        
        ConnectionFactory factory = new ConnectionFactory();
        
        try(Connection c = factory.obtemConexao();
            PreparedStatement ps = c.prepareStatement(sql)){
            
            ps.setInt(1, userAtual.getId_user());
            
            ps.executeUpdate();
            
            TabelaUsersAdmin telaTabelaAdmin = new TabelaUsersAdmin();
            telaTabelaAdmin.setVisible(true);
            telaTabelaAdmin.setLocationRelativeTo(null);
            this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_admDeletarButtonActionPerformed

    private void admEditarNomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admEditarNomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admEditarNomeTextFieldActionPerformed

    private void admEditarIdadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admEditarIdadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admEditarIdadeTextFieldActionPerformed

    private void admEditarIdadeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admEditarIdadeTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        // !Character é uma classe utilitária do java; .isDigit verifica se o valor recebido é um número, se for diferente de número passa.
        if (!Character.isDigit(c) || admEditarIdadeTextField.getText().length() >= 3){
            evt.consume(); // deleta tudo que não for número.
        }
    }//GEN-LAST:event_admEditarIdadeTextFieldKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarUserAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admCancelarButton;
    private javax.swing.JButton admDeletarButton;
    private javax.swing.JTextField admEditarEmailTextField;
    private javax.swing.JTextField admEditarIdadeTextField;
    private javax.swing.JTextField admEditarNomeTextField;
    private javax.swing.JButton admSalvarButton;
    private javax.swing.JCheckBox admTipoAdminCheckBox;
    private javax.swing.JCheckBox admTipoComumCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
