package com.mycompany.sistemacuradoria;

import java.sql.Connection;
import java.sql.PreparedStatement;

public class EditarCategoriaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCategoriaAdmin.class.getName());

    private Categoria categoriaAtual;
    
    /**
     * Creates new form EditarCategoriaAdmin
     */
    public EditarCategoriaAdmin() {
        initComponents();
    }
    
    public EditarCategoriaAdmin(Categoria categoria){
        initComponents();
        this.categoriaAtual = categoria;
        carregarDadosCategoria();
    }
    
    public void carregarDadosCategoria(){
        if(categoriaAtual != null){
            editarNomeCategoriaTextField.setText(categoriaAtual.getNomeCategoria());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvarEditarCategoriaButton = new javax.swing.JButton();
        editarNomeCategoriaTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        deletarCategoriaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salvarEditarCategoriaButton.setText("Salvar");
        salvarEditarCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarEditarCategoriaButtonActionPerformed(evt);
            }
        });

        editarNomeCategoriaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        deletarCategoriaButton.setText("Deletar");
        deletarCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarCategoriaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvarEditarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(editarNomeCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(editarNomeCategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarEditarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(deletarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarEditarCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarEditarCategoriaButtonActionPerformed
        // TODO add your handling code here:
        String sql = "update tb_categoria set categoria = ? where id_categoria = ?";
        
        String novoNomeCategoria = editarNomeCategoriaTextField.getText();
        
        if (novoNomeCategoria.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "O nome da categoria não pode ser vazio.", "Erro de Entrada", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        ConnectionFactory factory = new ConnectionFactory();
        
        try(Connection c = factory.obtemConexao();
            PreparedStatement ps = c.prepareStatement(sql)){
            
            ps.setString(1, novoNomeCategoria);
            ps.setInt(2, categoriaAtual.getIdCategoria());
            
            ps.executeUpdate();
            
            TabelaCategoriaAdmin telaTabelaCategoria = new TabelaCategoriaAdmin();
            telaTabelaCategoria.setVisible(true);
            telaTabelaCategoria.setLocationRelativeTo(null);
            this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_salvarEditarCategoriaButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        TabelaCategoriaAdmin telaTabelaCategoria = new TabelaCategoriaAdmin();
        telaTabelaCategoria.setVisible(true);
        telaTabelaCategoria.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void deletarCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarCategoriaButtonActionPerformed
        // TODO add your handling code here:
        String sql = "delete from tb_categoria where id_categoria = ?";
        
        ConnectionFactory factory = new ConnectionFactory();
        
        try(Connection c = factory.obtemConexao();
            PreparedStatement ps = c.prepareStatement(sql)){
            
            ps.setInt(1, categoriaAtual.getIdCategoria());
            
            ps.executeUpdate();
            
            TabelaCategoriaAdmin telaTabelaCategoria = new TabelaCategoriaAdmin();
            telaTabelaCategoria.setVisible(true);
            telaTabelaCategoria.setLocationRelativeTo(null);
            this.dispose();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_deletarCategoriaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarCategoriaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton deletarCategoriaButton;
    private javax.swing.JTextField editarNomeCategoriaTextField;
    private javax.swing.JButton salvarEditarCategoriaButton;
    // End of variables declaration//GEN-END:variables
}
