/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacuradoria;

import java.util.List;

/**
 *
 * @author Pichau
 */
public class TabelaUsersAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelaUsersAdmin.class.getName());

    /**
     * Creates new form TabelaUsersAdmin
     */
    public TabelaUsersAdmin() {
        initComponents();
        
        inicializarTabelaUsers(); 
        
        adicionarClique();
    }
    
    public void inicializarTabelaUsers(){
        // Carregar os dados
        UserDAO dao = new UserDAO();
        List<User> listaUser = dao.listaUsers();
        
        // Criar uma instância do seu modelo personalizado
        UserTableModel tableModel = new UserTableModel(listaUser);
        
        // Aplicar modelo JTable
        jTable1.setModel(tableModel);
        
        // Permite ordenar clicando no cabeçalho
        jTable1.setAutoCreateRowSorter(true);
    }
    
    public void adicionarClique(){
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                if(evt.getClickCount() == 1){
                    abrirDetalhesUser();
                }
            }
        });
    }
    
    public void abrirDetalhesUser(){
        int linhaView = jTable1.getSelectedRow(); 
    
        if (linhaView >= 0) {
            // Mapear a linha selecionada para a linha original do modelo (importante para tabelas ordenadas)
            int linhaModel = jTable1.convertRowIndexToModel(linhaView);

            // Obtém o modelo que você aplicou
            UserTableModel model = (UserTableModel) jTable1.getModel();

            // Obtém o objeto Usuario
            User user = model.getUser(linhaModel);

            // ABRIR A TELA DE DETALHES/EDIÇÃO
            // Substitua 'TelaDetalhesUsuario' pelo nome da sua tela de edição
            // TelaDetalhesUsuario telaDetalhes = new TelaDetalhesUsuario(usuario, this);
            // telaDetalhes.setVisible(true);

            System.out.println("Usuário selecionado para edição: " + user.getNome()); // Linha de teste
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TabelaUsersAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
