package com.mycompany.sistemacuradoria;

import java.util.List;

public class TabelaCategoriaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelaCategoriaAdmin.class.getName());

    /**
     * Creates new form TabelaCategoriaAdmin
     */
    public TabelaCategoriaAdmin() {
        initComponents();
        
        inicializarTabelaCategorias();
        
        adicionarClique();
    }
    
    public void inicializarTabelaCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> listaCategoria = dao.buscarTodas();
        
        CategoriaTableModel tableModel = new CategoriaTableModel(listaCategoria);
        
        jTable1.setModel(tableModel);
        jTable1.setAutoCreateRowSorter(true);
        
    }
    
    public void adicionarClique(){
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                if(evt.getClickCount() == 2){
                    abrirDetalheCategoria();
                }
            }
        });
    }
    
    public void abrirDetalheCategoria(){
        int linhaView = jTable1.getSelectedRow();
        
        if(linhaView >= 0){
            int linhaModel = jTable1.convertRowIndexToModel(linhaView);
            
            CategoriaTableModel model = (CategoriaTableModel) jTable1.getModel();
            
            Categoria categoria = model.getCategoria(linhaModel);
            
            EditarCategoriaAdmin telaEditar = new EditarCategoriaAdmin(categoria);
            telaEditar.setVisible(true);
            telaEditar.setLocationRelativeTo(null);
            this.dispose();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cadastrarCategoriaButton = new javax.swing.JButton();
        usuarioAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cadastrarCategoriaButton.setText("Add Categoria");
        cadastrarCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCategoriaButtonActionPerformed(evt);
            }
        });

        usuarioAdminButton.setText("Usuarios");
        usuarioAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCategoriaButtonActionPerformed
        // TODO add your handling code here:
        AddCategoria telaAddCategoria = new AddCategoria();
        
        telaAddCategoria.setVisible(true);
        telaAddCategoria.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cadastrarCategoriaButtonActionPerformed

    private void usuarioAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioAdminButtonActionPerformed
        // TODO add your handling code here:
        TabelaUsersAdmin telaUser = new TabelaUsersAdmin();
        telaUser.setVisible(true);
        telaUser.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_usuarioAdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TabelaCategoriaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarCategoriaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton usuarioAdminButton;
    // End of variables declaration//GEN-END:variables
}
