package com.mycompany.sistemacuradoria;

import java.util.List;

public class TabelaUsersAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabelaUsersAdmin.class.getName());
    
    /**
     * Creates new form TabelaUsersAdmin
     */
    public TabelaUsersAdmin() {
        initComponents();
        
        inicializarTabelaUsers(); 
        
        adicionarClique();
    }
    
    public void inicializarTabelaUsers(){
        // Carregar os dados
        UserDAO dao = new UserDAO();
        List<User> listaUser = dao.listaUsers();
        
        // Criar uma instância do seu modelo personalizado
        UserTableModel tableModel = new UserTableModel(listaUser);
        
        // Aplicar modelo JTable
        jTable1.setModel(tableModel);
        
        // Permite ordenar clicando no cabeçalho
        jTable1.setAutoCreateRowSorter(true);
    }
    
    public void adicionarClique(){
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
                if(evt.getClickCount() == 2){
                    abrirDetalhesUser();
                }
            }
        });
    }
    
    public void abrirDetalhesUser(){
        int linhaView = jTable1.getSelectedRow(); 
    
        if (linhaView >= 0) {
            // Mapear a linha selecionada para a linha original do modelo (importante para tabelas ordenadas)
            int linhaModel = jTable1.convertRowIndexToModel(linhaView);

            // Obtém o modelo que você aplicou
            UserTableModel model = (UserTableModel) jTable1.getModel();

            // Obtém o objeto Usuario
            User user = model.getUser(linhaModel);

            // ABRIR A TELA DE DETALHES/EDIÇÃO
            // Substitua 'TelaDetalhesUsuario' pelo nome da sua tela de edição
            // TelaDetalhesUsuario telaDetalhes = new TelaDetalhesUsuario(usuario, this);
            // telaDetalhes.setVisible(true);
            
            EditarUserAdmin editarUser = new EditarUserAdmin(user);
            editarUser.setVisible(true);
            editarUser.setLocationRelativeTo(null);
            this.dispose();

            System.out.println("Usuário selecionado para edição: " + user.getNome()); // Linha de teste
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addCategoriaButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        addCategoriaButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        addCategoriaButton.setText("Categoria");
        addCategoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoriaButtonActionPerformed(evt);
            }
        });

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        addCategoriaButton1.setText("Add Usuario");
        addCategoriaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoriaButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(addCategoriaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(addCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCategoriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoriaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCategoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoriaButtonActionPerformed
        // TODO add your handling code here:
        
        TabelaCategoriaAdmin telaCategoria = new TabelaCategoriaAdmin();
        telaCategoria.setVisible(true);
        telaCategoria.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_addCategoriaButtonActionPerformed

    private void addCategoriaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoriaButton1ActionPerformed
        // TODO add your handling code here:
        CadastroPorAdm telaCadastroPorAdm = new CadastroPorAdm();
        telaCadastroPorAdm.setVisible(true);
        telaCadastroPorAdm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_addCategoriaButton1ActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        Login telaLogin = new Login();
        telaLogin.setVisible(true);
        telaLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TabelaUsersAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoriaButton;
    private javax.swing.JButton addCategoriaButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
