package com.mycompany.sistemacuradoria;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class TelaPosts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPosts.class.getName());
    
    private int idUser;
    
    /**
     * Creates new form TelaPosts
     */
    public TelaPosts(int idUser) {
        this.idUser = idUser;
        
        initComponents();
        carregarPosts(this.idUser);
    }
    
    private JPanel criarCard(String titulo, String autor, String conteudo, int idCategoria, int idUser, String nomeUser, String nomeCategoria) {
        JPanel card = new JPanel();

        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        card.setBackground(Color.WHITE);
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 230));

        JLabel lblTitulo = new JLabel(titulo);
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblTitulo.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel lblAutor = new JLabel("créditos: " + autor);
        lblAutor.setFont(new Font("Segoe UI", Font.ITALIC, 12));
        lblAutor.setAlignmentX(Component.CENTER_ALIGNMENT);

        JTextArea txtConteudo = new JTextArea(conteudo);
        txtConteudo.setLineWrap(true);
        txtConteudo.setWrapStyleWord(true);
        txtConteudo.setEditable(false);
        txtConteudo.setBackground(new Color(245, 245, 245));

        JScrollPane scroll = new JScrollPane(txtConteudo);
        scroll.setBorder(null);
        scroll.setMaximumSize(new Dimension(500, 80));
        scroll.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel lblUser = new JLabel("Publicado por: " + nomeUser);
        lblUser.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblUser.setForeground(Color.DARK_GRAY);
        lblUser.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel lblCategoria = new JLabel("Categoria: " + nomeCategoria);
        lblCategoria.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblCategoria.setForeground(Color.GRAY);
        lblCategoria.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Adicionando ao card
        card.add(lblTitulo);
        card.add(lblAutor);
        card.add(Box.createRigidArea(new Dimension(0, 8)));
        card.add(scroll);
        card.add(Box.createRigidArea(new Dimension(0, 8)));
        card.add(lblUser);
        card.add(lblCategoria);
        card.add(Box.createRigidArea(new Dimension(0, 12)));

        return card;
    }


    private void carregarPosts(int idUser){
        PostDAO dao = new PostDAO();
        
        List<Post> posts = dao.listarPost(idUser);
        
        jPanel.removeAll();
        
        for(Post p : posts){
            JPanel card = criarCard(
                    p.getTitulo(),
                    p.getAutor(),
                    p.getConteudo(),
                    p.getIdCategoria(),
                    p.getIdUser(),
                    p.getNomeUser(),
                    p.getNomeCategoria()
            );
            
            jPanel.add(card);
            jPanel.add(Box.createRigidArea(new Dimension(0, 10))); // espaço entre os cards
        }
        
        jPanel.revalidate();
        jPanel.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();
        criarPostButton = new javax.swing.JButton();
        sairPostButton = new javax.swing.JButton();
        todosPostButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setLayout(new javax.swing.BoxLayout(jPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane.setViewportView(jPanel);

        criarPostButton.setText("Criar Post");
        criarPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPostButtonActionPerformed(evt);
            }
        });

        sairPostButton.setText("Sair");
        sairPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairPostButtonActionPerformed(evt);
            }
        });

        todosPostButton.setText("Todos os posts");
        todosPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosPostButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(sairPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(todosPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criarPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criarPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todosPostButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPostButtonActionPerformed
        // TODO add your handling code here:
        CriarPost cp = new CriarPost(idUser);
        cp.setVisible(true);
        cp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_criarPostButtonActionPerformed

    private void sairPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairPostButtonActionPerformed
        // TODO add your handling code here:
        
        Login telaLogin = new Login();
        telaLogin.setVisible(true);
        telaLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_sairPostButtonActionPerformed

    private void todosPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosPostButtonActionPerformed
        // TODO add your handling code here:
        TelaPostsGeral tpg = new TelaPostsGeral(idUser);
        tpg.setVisible(true);
        tpg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_todosPostButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new TelaPosts(idUser).setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarPostButton;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton sairPostButton;
    private javax.swing.JButton todosPostButton;
    // End of variables declaration//GEN-END:variables
}
