package com.mycompany.sistemacuradoria;

import com.mycompany.sistemacuradoria.CategoriaDAO;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class TelaInteresse extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInteresse.class.getName());
    
    private int idUsuario;
    private List<JCheckBox> listaCheckBoxes = new ArrayList();
    private int contagemSelecionados = 0;

    /**
     * Creates new form TelaInteresse
     */
//    public TelaInteresse() {
//        initComponents();
//    }
    
    public TelaInteresse(int idUsuario){
        this.idUsuario = idUsuario;
        
        initComponents();
        inicializarInteresses();
    }
    
    private void inicializarInteresses(){
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> categorias = dao.buscarTodas();
        
        painelInteresses.removeAll();
        
        for (Categoria cat : categorias){
            JCheckBox cb = new JCheckBox(cat.getNomeCategoria());
            
            System.out.println("DEBUG TELA: Nome recebido = '" + cat.getNomeCategoria() + "'");
            
            cb.setForeground(java.awt.Color.BLACK);
            cb.setOpaque(false);
            
            cb.setMaximumSize(new java.awt.Dimension(500, 30)); 
            
            // 2. FORÇAR ALINHAMENTO À ESQUERDA (Necessário para BoxLayout X_AXIS)
            cb.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            
            cb.setActionCommand(String.valueOf(cat.getIdCategoria()));
            
            cb.addItemListener(new ItemListener(){
                @Override
                public void itemStateChanged(ItemEvent e){
                    if(e.getStateChange() == ItemEvent.SELECTED){
                        if (contagemSelecionados >= 2){
                            ((JCheckBox) e.getItem()).setSelected(false);
                            JOptionPane.showMessageDialog(null, "Você só pode selecionar 2 interesses!", "Limite Atingido", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        contagemSelecionados++;
                    }else if(e.getStateChange() == ItemEvent.DESELECTED){
                        contagemSelecionados--;
                    }
                }
            });
            
            listaCheckBoxes.add(cb);
            painelInteresses.add(cb);
        }
        
        painelInteresses.revalidate();
        painelInteresses.repaint();
    }
    
    private List<Integer> getInteressesSelecionados(){
        List <Integer> ids = new ArrayList<>();
        
        for (JCheckBox cb : listaCheckBoxes){
            if(cb.isSelected()){
                String idStr = cb.getActionCommand();
                ids.add(Integer.parseInt(idStr));
            }
        }
        
        return ids;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelInteresses = new javax.swing.JPanel();
        salvarButtonInteresse = new javax.swing.JButton();
        cancelarButtonInteresse1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(653, 600));

        painelInteresses.setPreferredSize(new java.awt.Dimension(500, 380));
        painelInteresses.setLayout(new javax.swing.BoxLayout(painelInteresses, javax.swing.BoxLayout.Y_AXIS));

        salvarButtonInteresse.setText("Salvar");
        salvarButtonInteresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonInteresseActionPerformed(evt);
            }
        });

        cancelarButtonInteresse1.setText("Cancelar");
        cancelarButtonInteresse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonInteresse1ActionPerformed(evt);
            }
        });

        jTextPane1.setBackground(new java.awt.Color(60, 63, 65));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextPane1.setText("Selecione até 2 interesses:");
        jTextPane1.setToolTipText("");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelInteresses, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarButtonInteresse1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarButtonInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelInteresses, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButtonInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButtonInteresse1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarButtonInteresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonInteresseActionPerformed
            List<Integer> idsSelecionados = getInteressesSelecionados();
            
            if(idsSelecionados.isEmpty()){
                JOptionPane.showMessageDialog(this, "Selecione pelo menos um interesse", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            CategoriaDAO dao = new CategoriaDAO();
            boolean sucesso = dao.salvarInteresse(this.idUsuario, idsSelecionados);
            
            if(sucesso){
                JOptionPane.showMessageDialog(this, "Interesses salvos com sucesso!", "Concluído", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Falha ao salvar interesses no banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_salvarButtonInteresseActionPerformed

    private void cancelarButtonInteresse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonInteresse1ActionPerformed
        // TODO add your handling code here:
        CategoriaDAO dao = new CategoriaDAO();
        Cadastro cadastro = new Cadastro();
        
        dao.cancelarInteresse(this.idUsuario);
        
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonInteresse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInteresse(999).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButtonInteresse1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel painelInteresses;
    private javax.swing.JButton salvarButtonInteresse;
    // End of variables declaration//GEN-END:variables
}
