package com.mycompany.sistemacuradoria;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;


public class TelaInteressePorAdm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInteressePorAdm.class.getName());

    private int idUsuario;
    private List<JCheckBox> listaCheckBoxes = new ArrayList();
    private int contagemSelecionados = 0;
    
    /**
     * Creates new form TelaInteressePorAdm
     */
    public TelaInteressePorAdm(int idUsuario) {
        this.idUsuario = idUsuario;
        
        initComponents();
        inicializarInteresses();
    }
    
    private void inicializarInteresses(){
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> categorias = dao.buscarTodas();
        
        painelInteresses.removeAll();
        
        for (Categoria cat : categorias){
            JCheckBox cb = new JCheckBox(cat.getNomeCategoria());
            
            System.out.println("DEBUG TELA: Nome recebido = '" + cat.getNomeCategoria() + "'");
            
            cb.setForeground(java.awt.Color.BLACK);
            cb.setOpaque(false);
            
            cb.setMaximumSize(new java.awt.Dimension(500, 30)); 
            
            // 2. FORÇAR ALINHAMENTO À ESQUERDA (Necessário para BoxLayout X_AXIS)
            cb.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            
            cb.setActionCommand(String.valueOf(cat.getIdCategoria()));
            
            cb.addItemListener(new ItemListener(){
                @Override
                public void itemStateChanged(ItemEvent e){
                    if(e.getStateChange() == ItemEvent.SELECTED){
                        if (contagemSelecionados >= 2){
                            ((JCheckBox) e.getItem()).setSelected(false);
                            JOptionPane.showMessageDialog(null, "Você só pode selecionar 2 interesses!", "Limite Atingido", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        contagemSelecionados++;
                    }else if(e.getStateChange() == ItemEvent.DESELECTED){
                        contagemSelecionados--;
                    }
                }
            });
            
            listaCheckBoxes.add(cb);
            painelInteresses.add(cb);
        }
        
        painelInteresses.revalidate();
        painelInteresses.repaint();
    }
    
    private List<Integer> getInteressesSelecionados(){
        List <Integer> ids = new ArrayList<>();
        
        for (JCheckBox cb : listaCheckBoxes){
            if(cb.isSelected()){
                String idStr = cb.getActionCommand();
                ids.add(Integer.parseInt(idStr));
            }
        }
        
        return ids;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInteresses = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        salvarPorAdmButtonInteresse = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelInteresses.setPreferredSize(new java.awt.Dimension(500, 380));
        painelInteresses.setLayout(new javax.swing.BoxLayout(painelInteresses, javax.swing.BoxLayout.Y_AXIS));

        jTextField1.setText("Selecione os interesses do usuário (max 2):");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        salvarPorAdmButtonInteresse.setText("Salvar");
        salvarPorAdmButtonInteresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPorAdmButtonInteresseActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarPorAdmButtonInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelInteresses, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelInteresses, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarPorAdmButtonInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void salvarPorAdmButtonInteresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPorAdmButtonInteresseActionPerformed
        // TODO add your handling code here:
        List<Integer> idsSelecionados = getInteressesSelecionados();
            
            if(idsSelecionados.isEmpty()){
                JOptionPane.showMessageDialog(this, "Selecione pelo menos um interesse", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            try {
                CategoriaDAO dao = new CategoriaDAO();
                boolean sucesso = dao.salvarInteresse(this.idUsuario, idsSelecionados);

                if(sucesso){
                    JOptionPane.showMessageDialog(this, "Interesses salvos com sucesso!", "Concluído", JOptionPane.INFORMATION_MESSAGE);

                    // ************ ESTE CÓDIGO FINALMENTE SERÁ EXECUTADO ************
                    TabelaUsersAdmin telaAdmin = new TabelaUsersAdmin();
                    telaAdmin.setVisible(true);
                    telaAdmin.setLocationRelativeTo(null);
                    
                    this.dispose();

                } else {
                    // Este 'else' pode ser ativado se o DAO retornar false (e não lançar exceção)
                    JOptionPane.showMessageDialog(this, "Falha ao salvar interesses no banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                // Bloco CATCH ESSENCIAL: Captura a falha do banco (SQLException, etc.)
                JOptionPane.showMessageDialog(this, "Erro de banco de dados ao salvar interesses: " + e.getMessage(), "Erro Crítico", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Imprime o erro no console
            }
    }//GEN-LAST:event_salvarPorAdmButtonInteresseActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        CategoriaDAO dao = new CategoriaDAO();
        CadastroPorAdm cadastro = new CadastroPorAdm();
        
        dao.cancelarInteresse(this.idUsuario);
        
        cadastro.setVisible(true);
        cadastro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInteressePorAdm(999).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel painelInteresses;
    private javax.swing.JButton salvarPorAdmButtonInteresse;
    // End of variables declaration//GEN-END:variables
}
